Go back to capybara-webkit instead of poltergeist.
There are a couple of intermittent errors on CI with poltergeist and I
don't have time to debug them.

This reverts commit 74d3a7d63a3d024d36858330e95c8aa7bd6967e2.

The errors are:

test: Employed person who started 26 weeks before qualifying week (which
is in the future), changing due date should prefill the date selections.
(MaternityAnswerJavascriptTest):
Capybara::ElementNotFound: Unable to find css
"select[name='response[day]']"
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/node/finders.rb:154:in
`raise_find_error'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/node/finders.rb:27:in
`block in find'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/node/base.rb:46:in
`wait_until'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/node/finders.rb:27:in
`find'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/node/element.rb:177:in
`block in find'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/node/base.rb:46:in
`wait_until'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/node/element.rb:177:in
`find'
    (eval):2:in `find'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/dsl.rb:161:in
`find'
    /mnt/jenkins/workspace/Smart_Answers/test/integration/maternity_answer_logic.rb:134:in
`block (6 levels) in should_implement_maternity_answer_logic'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/session.rb:192:in
`within'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/capybara-1.1.2/lib/capybara/dsl.rb:161:in
`within'
    /mnt/jenkins/workspace/Smart_Answers/test/integration/maternity_answer_logic.rb:133:in
`block (5 levels) in should_implement_maternity_answer_logic'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in
`call'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in
`block in create_test_from_should_hash'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/mocha-0.10.0/lib/mocha/integration/mini_test/version_142_to_172.rb:27:in
`run'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/testing/setup_and_teardown.rb:35:in
`block in run'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/callbacks.rb:417:in
`_run_setup_callbacks'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/callbacks.rb:81:in
`run_callbacks'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/testing/setup_and_teardown.rb:34:in
`run'

  2) Error:
test: Employed person who started 26 weeks before qualifying week (which
is in the future), changing due date should redisplay the question.
(MaternityAnswerJavascriptTest):
RuntimeError: Expected question 'When is your baby due?', but found '4
Will you still be in the same job on 12 August 2012?'
    /mnt/jenkins/workspace/Smart_Answers/test/integration/smart_answer_test_helper.rb:9:in
`rescue in expect_question'
    /mnt/jenkins/workspace/Smart_Answers/test/integration/smart_answer_test_helper.rb:5:in
`expect_question'
    /mnt/jenkins/workspace/Smart_Answers/test/integration/maternity_answer_logic.rb:129:in
`block (5 levels) in should_implement_maternity_answer_logic'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in
`call'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in
`block in create_test_from_should_hash'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/mocha-0.10.0/lib/mocha/integration/mini_test/version_142_to_172.rb:27:in
`run'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/testing/setup_and_teardown.rb:35:in
`block in run'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/callbacks.rb:417:in
`_run_setup_callbacks'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/callbacks.rb:81:in
`run_callbacks'
    /home/jenkins/bundles/Smart_Answers/ruby/1.9.1/gems/activesupport-3.1.3/lib/active_support/testing/setup_and_teardown.rb:34:in
`run'